version: "3.9"

services:
  api:
    build: .
    ports:
      - ${PORT}:${PORT}
    container_name: api_nest
    depends_on:
      - postgres
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      STAGE: ${STAGE}
  


  postgres:
    image: postgres:14.6
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: inventory_db
    volumes:
      - postgres_db:/var/lib/postgresql/data

    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 2s
      retries: 5



volumes:
  postgres_db: