version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    container_name: api_nest
    image: test_app:1.0.1
    user: 'node'
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:14.6
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: inventory_db
    volumes:
      - postgres_db:/var/lib/postgresql/data



volumes:
  postgres_db:
